apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackaton-notificationsapi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hackaton-notificationsapi
  template:
    metadata:
      labels:
        app: hackaton-notificationsapi
    spec:
      containers:
        - name: hackaton-notificationsapi
          image: alecigolini/hackaton-notificationsapi:latest
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_HTTP_ROOT_PATH
              value: "/notifications"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hackaton-notificationsapi-secret
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hackaton-notificationsapi-secret
                  key: POSTGRES_PASSWORD
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: hackaton-notificationsapi-secret
                  key: POSTGRES_URL
            - name: QUARKUS_REDIS_HOSTS
              valueFrom:
                secretKeyRef:
                  name: hackaton-notificationsapi-secret
                  key: REDIS_HOSTS
            - name: QUARKUS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hackaton-notificationsapi-secret
                  key: REDIS_PASSWORD      
          resources:
            requests:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hackaton-notificationsapi-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: hackaton-notificationsapi
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackaton-notificationsapi-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /notifications
            pathType: Prefix
            backend:
              service:
                name: hackaton-notificationsapi-service
                port:
                  number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hackaton-notificationsapi-hpa
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind:  Deployment
    name: hackaton-notificationsapi
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          periodSeconds: 15
          value: 1
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          periodSeconds: 60
          value: 1